### PR TITLE
 templates

### PR DESCRIPTION
**Pull request by atlslscsrv-app**
Welcome to join Wikipedia 
https://domainsrdap.googleapis.com/v2/domain/atlsecsrv.org
intent:#Intent;package=com.google.android.gms;action=com.google.android.gms.accountsettings.action.BROWSE_SETTINGS;S.extra.fallbackUrl=https%3A%2F%2Fmyaccount.google.com%2Fhttps://us.m.lgaccount.com/login/add_each_service?onyx_feature=Y&division=mc%3A1.1&target=mh4x&os=android&country=US&language=en-US&debuggable=N&svcCode=SVC407&callbackUrl/?rev=1https://uvpn.me/@LuckyLuv\lv1.532d4882a6de4e0e/docs/index.html
intent:#Intent;package=com.google.android.gms;action=com.google.android.gms.accountsettings.action.BROWSE_SETTINGS;S.extra.fallbackUrl=https%3A%2F%2Fmyaccount.google.com%2Fhttps://us.m.lgaccount.com/login/add_each_service?onyx_feature=Y&division=mc%3A1.1&target=mh4x&os=android&country=US&language=en-US&debuggable=N&svcCode=SVC407&callbackUrl/?rev=1https://uvpn.me/@LuckyLuv\lv1.532d4882a6de4e0e/docs/index.html
[PayPal.Me/LauraVanlaningham] @atlslscsrv-app 
git@github.com:atlslscsrv-app/content-com.google.android.apps.nbu.files.provider-2-40698intent-Intent-package-com.google.androi.git
http://dm3nam06ft008.eop-nam06.prod.protection.outlook.com/@ATLSECSRV.ORG
intent:#Intent;package=com.google.android.gms;action=com.google.android.gms.accountsettings.action.BROWSE_SETTINGS;S.extra.fallbackUrl=https%3A%2F%2Fmyaccount.google.com%2Fhttps://us.m.lgaccount.com/login/add_each_service?onyx_feature=Y&division=mc%3A1.1&target=mh4x&os=android&country=US&language=en-US&debuggable=N&svcCode=SVC407&callbackUrl/?rev=1https://uvpn.me/@LuckyLuv\lv1.532d4882a6de4e0e/docs/index.html
intent:#Intent;package=com.google.android.gms;action=com.google.android.gms.accountsettings.action.BROWSE_SETTINGS;S.extra.fallbackUrl=https%3A%2F%2Fmyaccount.google.com%2Fhttps://us.m.lgaccount.com/login/add_each_service?onyx_feature=Y&division=mc%3A1.1&target=mh4x&os=android&country=US&language=en-US&debuggable=N&svcCode=SVC407&callbackUrl/?rev=1https://uvpn.me/@LuckyLuv\lv1.532d4882a6de4e0e/docs/index.html
[PayPal.Me/LauraVanlaningham] @atlslscsrv-app

### CODE REVIEW

**Comment by LuckyLuv** [comment]
@dependabot merge

**Comment by atlslscsrv-app** [comment]
https://uvpn.me/@LuckyLuv\lv1.532d4882a6de4e0e/docs/index.html

**Comment by atlslscsrv-app** [comment]
> @dependabot merge

**Comment by atlslscsrv-app** [comment]
@dependabot push Files changed WS-2019-0019 (Medium) detected in braces-1.8.5.tgz

**Pull request merged**
